package tto.datas 
{
	import feathers.data.ListCollection;
	import tto.Game;
	/**
	 * ...
	 * @author Mao
	 */
	public class NPCs
	{
		
		public static function get LIST():Array {
			return NPCs[String(Game.PROFILE_DATAS.MODE).toUpperCase() + 'NPCS'];
		}
		
		private static const FF14_NPCS:Array = [
			new NPC( {
				id:1,
				name:'STR_NPC_TT_Master',
				iconID:'tt-master',
				rules:[tripleTriadRules.RULE_ALL_OPEN],
				fetishesCards:[2, 4, 5, 7, 13],
				cards:[],
				level:NPC.LEVEL_NOVICE,
				matchFee:5,
				MGPReward: { w:10, d:4, l:1 },
				difficulty:1,
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.02 }, { type:"card", card:4, rate:0.25 }, { type:"card", card:13, rate:0.20 } ]
			}),
			new NPC( {
				id:2,
				name:'STR_NPC_Jonas',
				iconID:'jonas',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_SAME],
				fetishesCards:[23, 3, 4],
				cards:[11, 15, 20, 26],
				level:NPC.LEVEL_NOVICE,
				matchFee:10,
				MGPReward: { w:22, d:8, l:3 },
				difficulty:2,
				itemRewards:[{type:"card", card:15, rate:0.25}, {type:"card", card:20, rate:0.20}]
			}),
			new NPC( {
				id:3,
				name:'STR_NPC_Guhtwint',
				iconID:'guhtwint',
				rules:[tripleTriadRules.RULE_THREE_OPEN, tripleTriadRules.RULE_PLUS],
				fetishesCards:[38, 26, 23],
				cards:[41, 27, 13, 11],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:32, d:12, l:4 },
				difficulty:3,
				itemRewards:[ {type:"card", card:13, rate:0.20}, {type:"card", card:27, rate:0.125}]
			}),
			new NPC( {
				id:4,
				name:'STR_NPC_Aurifort',
				iconID:'aurifort',
				rules:[tripleTriadRules.RULE_THREE_OPEN, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[],
				cards:[51, 43, 24, 38, 33, 27, 12, 35],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:50, d:20, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:12, rate:0.20}, {type:"card", card:27, rate:0.125}]
			}),
			new NPC( {
				id:5,
				name:'STR_NPC_Ruhtwyda',
				iconID:'ruhtwyda',
				rules:[tripleTriadRules.RULE_ASCENSION, tripleTriadRules.RULE_SUDDEN_DEATH, tripleTriadRules.RULE_ALL_OPEN],
				fetishesCards:[59, 56, 47],
				cards:[58, 50, 57, 45],
				level:NPC.LEVEL_AVERAGE,
				matchFee:25,
				MGPReward: { w:59, d:0, l:8 },
				difficulty:6,
				itemRewards:[{type:"card", card:45, rate:0.15}, {type:"card", card:50, rate:0.125}]
			}),
			new NPC( {
				id:6,
				name:'STR_NPC_King_Elmer',
				iconID:'elmer',
				rules:[tripleTriadRules.RULE_PLUS],
				fetishesCards:[61, 50, 45],
				cards:[62, 39, 49, 41],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:117, d:46, l:17 },
				difficulty:12,
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:45, rate:0.125}, {type:"card", card:61, rate:0.05}]
			}),
			new NPC( {
				id:7,
				name:'STR_NPC_Memeroon',
				iconID:'memeroon',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_SAME],
				fetishesCards:[37, 14, 1],
				cards:[21, 12, 7, 2],
				level:NPC.LEVEL_NOVICE,
				matchFee:10,
				MGPReward: { w:23, d:9, l:3 },
				difficulty:2,
				itemRewards:[{type:"card", card:2, rate:0.4},{type:"card", card:14, rate:0.25}, {type:"card", card:37, rate:0.125}]
			}),
			new NPC( {
				id:8,
				name:'STR_NPC_Trachtoum',
				iconID:'tratchoum',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[41, 49, 39],
				cards:[38, 22, 47, 20],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:47, d:18, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:20, rate:0.4}, {type:"card", card:41, rate:0.125}],
				availability: { begins:20, ends:8 }// in hours
			}),
			new NPC( {
				id:9,
				name:'STR_NPC_Baderon',
				iconID:'baderon',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[28, 29, 30],
				cards:[56, 38, 49, 27, 21],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:49, d:19, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:18, rate:0.4},{type:"card", card:29, rate:0.25}]
			}),
			new NPC( {
				id:10,
				name:'STR_NPC_Mimidoa',
				iconID:'mimidoa',
				rules:[tripleTriadRules.RULE_THREE_OPEN, tripleTriadRules.RULE_ASCENSION],
				fetishesCards:[54, 50, 33],
				cards:[37, 27, 25],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:47, d:19, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:21, rate:0.25},{type:"card", card:27, rate:0.25},{type:"card", card:33, rate:0.25}]
			}),
			new NPC( {
				id:11,
				name:"STR_NPC_Rashaht_Rhiki",
				iconID:'rashaht-rhiki',
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[65, 54, 41],
				cards:[58, 38, 50, 49, 30, 24],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:44, l:16 },
				difficulty:11,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.125 }, {type:"card", card:49, rate:0.33}, {type:"card", card:54, rate:0.22}, {type:"card", card:65, rate:0.05}],
				availability: { begins:14, ends:19 }// in hours
			}),
			new NPC( {
				id:12,
				name:"STR_NPC_Gegeruju",
				iconID:'gegeruju',
				rules:[tripleTriadRules.RULE_SWAP, tripleTriadRules.RULE_SUDDEN_DEATH],
				fetishesCards:[63, 56, 49],
				cards:[66, 65, 31, 30, 55],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:116, d:0, l:17 },
				difficulty:12,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.125 }, {type:"card", card:49, rate:0.125}, {type:"card", card:56, rate:0.1}]
			}),
			new NPC( {
				id:13,
				name:"STR_NPC_Maisenta",
				iconID:'maisenta',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[36, 7, 10],
				cards:[24, 16, 8],
				level:NPC.LEVEL_NOVICE,
				matchFee:10,
				MGPReward: { w:22, d:8, l:3 },
				difficulty:2,
				itemRewards:[{type:"card", card:8, rate:0.2}, {type:"card", card:12, rate:0.2}, {type:"card", card:16, rate:0.2}]
			}),
			new NPC( {
				id:14,
				name:"STR_NPC_Roger",
				iconID:'roger',
				rules:[tripleTriadRules.RULE_ALL_OPEN],
				fetishesCards:[26, 9, 13],
				cards:[25, 15, 6, 5],
				level:NPC.LEVEL_NOVICE,
				matchFee:10,
				MGPReward: { w:22, d:8, l:3 },
				difficulty:2,
				itemRewards:[{type:"card", card:5, rate:0.25}, {type:"card", card:9, rate:0.25}]
			}),
			new NPC( {
				id:15,
				name:"STR_NPC_Mother_Miounne",
				iconID:'miounne',
				rules:[tripleTriadRules.RULE_THREE_OPEN, tripleTriadRules.RULE_REVERSE],
				fetishesCards:[30, 29, 28],
				cards:[48, 12, 35, 11, 5],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:32, d:12, l:4 },
				difficulty:3,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.05 }, {type:"card", card:12, rate:0.2}, {type:"card", card:16, rate:0.2}, {type:"card", card:30, rate:0.125}]
			}),
			new NPC( {
				id:16,
				name:"STR_NPC_Fhobhas",
				iconID:'fhobhas',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[45, 36, 14],
				cards:[23, 25, 5, 34, 6],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:33, d:13, l:4 },
				difficulty:3,
				itemRewards:[{type:"card", card:36, rate:0.125}]
			}),
			new NPC( {
				id:17,
				name:"STR_NPC_Wymond",
				iconID:'wymond',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[22, 28, 31],
				cards:[40, 26, 8, 4, 7],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:33, d:13, l:4 },
				difficulty:3,
				itemRewards:[{type:"card", card:8, rate:0.5},{type:"card", card:141, rate:0.1}]
			}),
			new NPC( {
				id:18,
				name:"STR_NPC_Momodi",
				iconID:'momodi',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[28, 29, 30],
				cards:[46, 8, 36, 13, 10],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:33, d:13, l:4 },
				difficulty:3,
				itemRewards:[{type:"card", card:12, rate:0.2}, {type:"card", card:28, rate:0.1}, {type:"card", card:29, rate:0.1}]
			}),
			new NPC( {
				id:19,
				name:"STR_NPC_Momo",
				iconID:'momo',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 20, 43],
				level:NPC.LEVEL_INITIATE,
				matchFee:15,
				MGPReward: { w:33, d:13, l:4 },
				difficulty:4,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.05 }, {type:"card", card:20, rate:0.25}, {type:"card", card:43, rate:0.125}]
			}),
			new NPC( {
				id:20,
				name:"STR_NPC_Helmhart",
				iconID:'helmhart',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[],
				cards:[60, 45, 34, 41, 27, 22],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:48, d:19, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:22, rate:0.25}, {type:"card", card:34, rate:0.25}],
				availability: { begins:10, ends:20 }// in hours
			}),
			new NPC( {
				id:21,
				name:"STR_NPC_Joellaut",
				iconID:'joellaut',
				rules:[tripleTriadRules.RULE_THREE_OPEN, tripleTriadRules.RULE_PLUS],
				fetishesCards:[38, 33, 27],
				cards:[50, 26, 42, 15, 59],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:48, d:19, l:7 },
				difficulty:5,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.05 }, {type:"card", card:15, rate:0.4}, {type:"card", card:59, rate:0.1}]
			}),
			new NPC( {
				id:22,
				name:"STR_NPC_Fufulupa",
				iconID:'fufulupa',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[46, 28, 33],
				cards:[20, 19, 67, 13],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:48, d:19, l:7 },
				difficulty:5,
				itemRewards:[{type:"card", card:25, rate:0.4},{type:"card", card:46, rate:0.2}]
			}),
			new NPC( {
				id:24,
				name:"STR_NPC_Piralnaut",
				iconID:'piralnaut',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[56, 44, 48],
				cards:[38, 24, 35, 30],
				level:NPC.LEVEL_AVERAGE,
				matchFee:20,
				MGPReward: { w:50, d:20, l:7 },
				difficulty:5,
				itemRewards:[ { type:"card", card:24, rate:0.2 }, { type:"card", card:35, rate:0.125 } ],
				availability: { begins:12, ends:20 }// in hours
			}),
			new NPC( {
				id:25,
				name:"STR_NPC_Sezul_Totoloc",
				iconID:'sezul-totoloc',
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[58, 51, 33],
				cards:[45, 47, 38],
				level:NPC.LEVEL_ADVANCED,
				matchFee:25,
				MGPReward: { w:52, d:20, l:7 },
				difficulty:5,
				itemRewards:[ { type:"card", card:33, rate:0.15 }, { type:"card", card:38, rate:0.15 }, { type:"card", card:58, rate:0.05 } ]
			}),
			new NPC( {
				id:26,
				name:"STR_NPC_Landenel",
				iconID:'landenel',
				rules:[tripleTriadRules.RULE_FALLEN_ACE, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[],
				cards:[52, 41, 34, 61, 40, 45, 32, 13],
				level:NPC.LEVEL_ADVANCED,
				matchFee:25,
				MGPReward: { w:53, d:21, l:7 },
				difficulty:5,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:0.05 },  { type:"card", card:41, rate:0.2 }, { type:"card", card:52, rate:0.125 } ]
			}),
			new NPC( {
				id:27,
				name:"STR_NPC_Buscarron",
				iconID:'buscarron',
				rules:[tripleTriadRules.RULE_ORDER],
				fetishesCards:[66, 52, 43],
				cards:[44, 48, 39, 42],
				level:NPC.LEVEL_ADVANCED,
				matchFee:25,
				MGPReward: { w:59, d:23, l:8 },
				difficulty:6,
				itemRewards:[ { type:"card", card:23, rate:0.4 }, { type:"card", card:48, rate:0.18 }, { type:"card", card:44, rate:0.2 } ]
			}),
			new NPC( {
				id:28,
				name:"STR_NPC_Ourdilic",
				iconID:'ourdilic',
				rules:[tripleTriadRules.RULE_ORDER],
				fetishesCards:[55, 51, 50],
				cards:[44, 26, 38, 33],
				level:NPC.LEVEL_ADVANCED,
				matchFee:25,
				MGPReward: { w:60, d:24, l:9 },
				difficulty:6,
				itemRewards:[{ type:"card", card:11, rate:0.5 }, { type:"card", card:26, rate:0.4 }, { type:"card", card:38, rate:0.3 } ]
			}),
			new NPC( {
				id:29,
				name:"STR_NPC_Marcette",
				iconID:'marcette',
				rules:[tripleTriadRules.RULE_CHAOS],
				fetishesCards:[52, 53, 57],
				cards:[47, 38, 44, 35, 42],
				level:NPC.LEVEL_ADVANCED,
				matchFee:25,
				MGPReward: { w:60, d:24, l:9 },
				difficulty:6,
				itemRewards:[ { type:"card", card:35, rate:0.3 }, { type:"card", card:42, rate:0.2 } ],
				availability: { begins:16, ends:8 }// in hours
			}),
			new NPC( {
				id:30,
				name:"STR_NPC_Hab",
				iconID:'hab',
				rules:[tripleTriadRules.RULE_DESCENSION],
				fetishesCards:[62, 45],
				cards:[67, 52, 46, 34, 3],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:104, d:41, l:15 },
				difficulty:10,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 },  { type:"card", card:45, rate:0.125 }, { type:"card", card:46, rate:0.125 }, { type:"card", card:62, rate:0.05 } ]
			}),
			new NPC( {
				id:31,
				name:"STR_NPC_Vorsaile_Heuloix",
				iconID:'vorsaile-heuloix',
				rules:[tripleTriadRules.RULE_ASCENSION],
				fetishesCards:[66, 56, 53],
				cards:[63, 58, 43, 48, 20],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:44, l:16 },
				difficulty:11,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, { type:"card", card:43, rate:0.2 },  { type:"card", card:48, rate:0.2 }, {type:"card", card:53, rate:0.05 }, { type:"card", card:66, rate:0.05 } ],
				availability: { begins:22, ends:3 }// in hours
			}),
			new NPC( {
				id:32,
				name:"STR_NPC_Swift",
				iconID:'swift',
				rules:[tripleTriadRules.RULE_CHAOS],
				fetishesCards:[67, 60, 55],
				cards:[63, 59, 46, 40],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:44, l:16 },
				difficulty:11,
				itemRewards:[ { type:"card", card:40, rate:0.2 }, { type:"card", card:59, rate:0.1 }, { type:"card", card:67, rate:0.05 }, { type:"card", card:113, rate:0.05 } ],
				availability: { begins:6, ends:11 }// in hours
			}),
			new NPC( {
				id:33,
				name:"STR_NPC_Rowena",
				iconID:'rowena',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:[47, 46, 50, 34, 29, 61, 60, 45],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:118, d:48, l:17 },
				difficulty:12,
				itemRewards:[ { type:"card", card:34, rate:0.5 }, { type:"card", card:60, rate:0.125 }]
			}),
			new NPC( {
				id:34,
				name:"STR_NPC_Indolent_Imperial",
				iconID:'indolent-imperial',
				rules:[tripleTriadRules.RULE_ASCENSION],
				fetishesCards:[64,61,47],
				cards:[42,37,27,32,31],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:120, d:48, l:18 },
				difficulty:12,
				itemRewards:[{ type:"card", card:31, rate:0.16 }, { type:"card", card:32, rate:0.22 }, { type:"card", card:47, rate:0.1 }, { type:"card", card:64, rate:0.05 }]
			}),
			new NPC( {
				id:35,
				name:"STR_NPC_Tataru",
				iconID:'tataru',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:[19, 33, 46, 49, 50, 62, 80],
				level:NPC.LEVEL_EXPERT,
				matchFee:35,
				MGPReward: { w:165, d:66, l:24 },
				difficulty:16,
				itemRewards:[ { type:"card", card:19, rate:0.4 }, { type:"card", card:50, rate:0.1 }, { type:"card", card:80, rate:0.01 }]
			}),
			new NPC( {
				id:36,
				name:"STR_NPC_PAPALYMO",
				iconID:'papalymo',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[21, 25, 28, 29, 30, 44, 45, 46, 48, 49, 50, 78],
				level:NPC.LEVEL_EXPERT,
				matchFee:35,
				MGPReward: { w:165, d:66, l:24 },
				difficulty:16,
				itemRewards:[ { type:"card", card:21, rate:0.2 }, {type:"card",  card:25, rate:0.2 }, { type:"card", card:78, rate:0.01 }]
			}),
			new NPC( {
				id:37,
				name:'STR_NPC_Lewena',
				iconID:'lewena',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_CHAOS],
				fetishesCards:[40,41,42,52],
				cards:[70,73,74],
				level:NPC.LEVEL_EXPERT,
				matchFee:40,
				MGPReward: { w:182, d:72, l:27 },
				difficulty:18,
				availability: { begins:21, ends:7 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:70, rate:0.05}, {type:"card", card:72, rate:0.05}, {type:"card", card:73, rate:0.05}]
			}),
			new NPC( {
				id:38,
				name:'STR_NPC_Okalkaya',
				iconID:"okalkaya",
				rules:[tripleTriadRules.RULE_ROULETTE, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[12,54,65,144,149],
				level:NPC.LEVEL_EXPERT,
				matchFee:20,
				MGPReward: { w:67, d:27, l:10 },
				difficulty:7,
				availability: { begins:19, ends:23 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:65, rate:0.05}, {type:"card", card:144, rate:0.05}]
			}),
			new NPC( {
				id:39,
				name:'STR_NPC_Mordyn',
				iconID:"mordyn",
				rules:[tripleTriadRules.RULE_SWAP, tripleTriadRules.RULE_SAME],
				fetishesCards:[],
				cards:[65,54,149,145,126,29,7],
				level:NPC.LEVEL_EXPERT,
				matchFee:20,
				MGPReward: { w:73, d:29, l:10 },
				difficulty:7,
				availability: { begins:19, ends:23 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:65, rate:0.05}, {type:"card", card:145, rate:0.05}]
			}),
			new NPC( {
				id:40,
				name:'STR_NPC_Wawalago',
				iconID:"wawalago",
				rules:[tripleTriadRules.RULE_SWAP, tripleTriadRules.RULE_CHAOS],
				fetishesCards:[63,49,28],
				cards:[48,89,42,73,75],
				level:NPC.LEVEL_EXPERT,
				matchFee:25,
				MGPReward: { w:64, d:25, l:9 },
				difficulty:6,
				availability: { begins:15, ends:3 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:89, rate:0.05}]
			}),
			new NPC( {
				id:41,
				name:'STR_NPC_Noes',
				iconID:"noes",
				rules:[tripleTriadRules.RULE_DESCENSION, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[42,52],
				cards:[36,81,35,43,30],
				level:NPC.LEVEL_EXPERT,
				matchFee:25,
				MGPReward: { w:64, d:25, l:9 },
				difficulty:6,
				availability: { begins:10, ends:20 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:81, rate:0.25}]
			}),
			new NPC( {
				id:42,
				name:'STR_NPC_Yayake',
				iconID:"yayake",
				rules:[tripleTriadRules.RULE_CHAOS, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[55,61],
				cards:[22,40,46,81,96],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:123, d:49, l:18 },
				difficulty:12,
				availability: { begins:9, ends:20 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:96, rate:0.25}]
			}),
			new NPC( {
				id:43,
				name:'STR_NPC_Yellow_Moon',
				iconID:"yellow-moon",
				rules:[tripleTriadRules.RULE_ASCENSION, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[],
				cards:[29,32,34,55,64,77,81,84],
				level:NPC.LEVEL_EXPERT,
				matchFee:25,
				MGPReward: { w:64, d:25, l:9 },
				difficulty:6,
				availability: { begins:22, ends:6 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:84, rate:0.1}]
			}),
			new NPC( {
				id:44,
				name:'STR_NPC_House_Fortemps_Manservant',
				iconID:"manservant",
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[93,95,116,121,133,134],
				level:NPC.LEVEL_EXPERT,
				matchFee:25,
				MGPReward: { w:48, d:19, l:7 },
				difficulty:5,
				availability: { begins:2, ends:9 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:121, rate:0.1}, {type:"card", card:133, rate:0.1}, {type:"card", card:134, rate:0.1}]
			}),
			new NPC( {
				id:45,
				name:'STR_NPC_Gibrillont',
				iconID:"gibrillont",
				rules:[tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:[89,56,88,62,58,50,19],
				level:NPC.LEVEL_AVERAGE,
				matchFee:25,
				MGPReward: { w:64, d:25, l:9 },
				difficulty:6,
				availability: { begins:2, ends:10 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:88, rate:0.1}]
			}),
			new NPC( {
				id:46,
				name:'STR_NPC_Elaisse',
				iconID:"elaisse",
				rules:[tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_CHAOS],
				fetishesCards:[],
				cards:[91,67,65,66,63,102],
				level:NPC.LEVEL_AVERAGE,
				matchFee:25,
				MGPReward: { w:112, d:44, l:16 },
				difficulty:11,
				availability: { begins:2, ends:6 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:102, rate:0.1}, {type:"card", card:142, rate:0.1}]
			}),
			new NPC( {
				id:47,
				name:'STR_NPC_Dominiac',
				iconID:"dominiac",
				rules:[tripleTriadRules.RULE_ORDER],
				fetishesCards:[101,96],
				cards:[93,89,86,88,38],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:73, d:29, l:10 },
				difficulty:7,
				availability: { begins:16, ends:20 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:101, rate:0.1}]
			}),
			new NPC( {
				id:48,
				name:'STR_NPC_Klynthota',
				iconID:"klynthota",
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[140,132,135,47,33,58],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:93, d:37, l:13 },
				difficulty:9,
				availability: { begins:23, ends:4 },
				itemRewards:[ { type:"potion", potion:'MGP_BOOST', rate:0.25 }, {type:"card", card:132, rate:0.1}, {type:"card", card:135, rate:0.1}, {type:"card", card:140, rate:0.1}, {type:"card", card:150, rate:0.1}]
			}),
			new NPC( {
				id:49,
				name:'STR_NPC_Linu_Vali',
				iconID:"linu-vali",
				rules:[tripleTriadRules.RULE_REVERSE, tripleTriadRules.RULE_CHAOS],
				fetishesCards:[],
				cards:[98,81,82,123,104,86,103],
				level:NPC.LEVEL_AVERAGE,
				matchFee:0,
				MGPReward: { w:0, d:0, l:0 },
				difficulty:4,
				availability: { begins:17, ends:23 },
				itemRewards:[ {type:"card", card:98, rate:0.1}, {type:"card", card:123, rate:0.1}]
			}),
			new NPC( {
				id:50,
				name:'STR_NPC_Laniaitte',
				iconID:"laniaitte",
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[98,103],
				cards:[58,104,93,89,96],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:110, d:44, l:16 },
				difficulty:11,
				availability: { begins:23, ends:2 },
				itemRewards:[ {type:"card", card:103, rate:0.1}, {type:"card", card:104, rate:0.1}]
			}),
			new NPC( {
				id:51,
				name:'STR_NPC_Marielle',
				iconID:"marielle",
				rules:[tripleTriadRules.RULE_ORDER],
				fetishesCards:[],
				cards:[63,86,65,93,96],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:124, d:49, l:18 },
				difficulty:12,
				availability: { begins:2, ends:10 },
				itemRewards:[ {type:"card", card:93, rate:0.1}, {type:"card", card:143, rate:0.1}]
			}),
			new NPC( {
				id:52,
				name:'STR_NPC_Idle_Imperial',
				iconID:"idle-imperial",
				rules:[tripleTriadRules.RULE_ASCENSION, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[],
				cards:[91,92,47,83,97,40,32],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:124, d:49, l:18 },
				difficulty:12,
				availability: { begins:21, ends:8 },
				itemRewards:[ {type:"card", card:91, rate:0.1}, {type:"card", card:119, rate:0.1}, {type:"card", card:151, rate:0.1}]
			}),
			new NPC( {
				id:53,
				name:'STR_NPC_Vath_Deftarm',
				iconID:"vath-deftarm",
				rules:[tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:[88,90,97,59,83,105,109],
				level:NPC.LEVEL_AVERAGE,
				matchFee:25,
				MGPReward: { w:86, d:34, l:12 },
				difficulty:9,
				itemRewards:[ {type:"card", card:97, rate:0.1}, {type:"card", card:109, rate:0.1}, {type:"card", card:85, rate:0.1}]
			}),
			new NPC( {
				id:54,
				name:'STR_NPC_Tapklix',
				iconID:"tapklix",
				rules:[tripleTriadRules.RULE_SWAP, tripleTriadRules.RULE_SAME],
				fetishesCards:[],
				cards:[136,117,49,107,106],
				level:NPC.LEVEL_AVERAGE,
				matchFee:25,
				MGPReward: { w:86, d:34, l:12 },
				difficulty:9,
				availability: { begins:14, ends:18 },
				itemRewards:[ {type:"card", card:117, rate:0.1}, {type:"card", card:136, rate:0.1}]
			}),
			new NPC( {
				id:55,
				name:'STR_NPC_Voracious_Vath',
				iconID:"voracious-vath",
				rules:[tripleTriadRules.RULE_SWAP, tripleTriadRules.RULE_ASCENSION],
				fetishesCards:[105,97],
				cards:[87,109,88,90,55,59],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:98, d:39, l:14 },
				difficulty:10,
				availability: { begins:6, ends:24 },
				itemRewards:[ {type:"card", card:117, rate:0.1}, {type:"card", card:136, rate:0.1}]
			}),
			new NPC( {
				id:56,
				name:'STR_NPC_Master_Mogzin',
				iconID:"mogzin",
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[90,153,20,124,43,99,108],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:120, d:48, l:18 },
				difficulty:12,
				availability: { begins:21, ends:3 },
				itemRewards:[ {type:"card", card:43, rate:0.1}, {type:"card", card:146, rate:0.1}, {type:"card", card:153, rate:0.1}]
			}),
			new NPC( {
				id:57,
				name:'STR_NPC_Marcechamp',
				iconID:"marcechamp",
				rules:[tripleTriadRules.RULE_REVERSE, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[],
				cards:[81,45,55,84,14,90,3],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:124, d:49, l:18 },
				difficulty:12,
				availability: { begins:19, ends:5 },
				itemRewards:[{type:"card", card:90, rate:0.1}]
			}),
			new NPC( {
				id:58,
				name:'STR_NPC_Mogmill',
				iconID:"mogmill",
				rules:[tripleTriadRules.RULE_ROULETTE, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[66,98,83],
				cards:[100,43,97,82],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:124, d:49, l:18 },
				difficulty:12,
				itemRewards:[{type:"card", card:82, rate:0.1},{type:"card", card:83, rate:0.1},{type:"card", card:108, rate:0.1},{type:"card", card:115, rate:0.1}]
			}),
			new NPC( {
				id:59,
				name:'STR_NPC_Midnight_Dew',
				iconID:"midnight-dew",
				rules:[tripleTriadRules.RULE_ROULETTE, tripleTriadRules.RULE_RANDOM],
				fetishesCards:[88,100,86],
				cards:[97,99,92,49],
				level:NPC.LEVEL_AVERAGE,
				matchFee:30,
				MGPReward: { w:124, d:49, l:18 },
				difficulty:12,
				itemRewards:[{type:"card", card:92, rate:0.1}]
			}),
			new NPC( {
				id:60,
				name:'STR_NPC_Seika',
				iconID:"seika",
				rules:[tripleTriadRules.RULE_REVERSE, tripleTriadRules.RULE_CHAOS],
				fetishesCards:[],
				cards:[18,107,14,106,117,15,17],
				level:NPC.LEVEL_AVERAGE,
				matchFee:35,
				MGPReward: { w:82, d:32, l:12 },
				difficulty:8,
				itemRewards:[{type:"card", card:106, rate:0.1},{type:"card", card:107, rate:0.1},{type:"card", card:117, rate:0.1}]
			}),
			new NPC( {
				id:99,
				name:"STR_NPC_QUEEN_OF_CARDS",
				iconID:'queen-of-cards',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:cards.getCardsByRarities([1,2,3,4,5], 'ff14_'),
				level:NPC.LEVEL_EXPERT,
				matchFee:40,
				MGPReward: { w:182, d:72, l:27 },
				difficulty:19,
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, { type:"card", card:77, rate:0.01 }]
			}),
		];
		
		
		
		
		
		
		private static const FF8_NPCS:Array = [
			new NPC( {
				id:1,
				name:"STR_NPC_KID",
				iconID:'kid',
				rules:[tripleTriadRules.RULE_ALL_OPEN],
				fetishesCards:[],
				cards:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 81],
				level:NPC.LEVEL_NOVICE,
				matchFee:5,
				MGPReward: { w:15, d:7, l:2 },
				itemRewards:[ { type:"card", card:10, rate:0.25 }, { type:"card", card:13, rate:0.25 }, { type:"card", card:81, rate:0.08 }]
			}),
			new NPC( {
				id:2,
				name:"STR_NPC_CHOCOBOY",
				iconID:'chocoboy',
				rules:[tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[],
				cards:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 78, 82],
				level:NPC.LEVEL_NOVICE,
				matchFee:5,
				MGPReward: { w:16, d:8, l:3 },
				itemRewards:[ { type:"card", card:16, rate:0.25 }, { type:"card", card:20, rate:0.25 }, { type:"card", card:78, rate:0.08 }, { type:"card", card:82, rate:0.08 }]
			}),
			new NPC( {
				id:2,
				name:"STR_NPC_UFO",
				iconID:'ufo',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_THREE_OPEN],
				fetishesCards:[48],
				cards:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
				level:NPC.LEVEL_NOVICE,
				matchFee:5,
				MGPReward: { w:18, d:9, l:4 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, { type:"card", card:11, rate:0.25 }, { type:"card", card:21, rate:0.25 }, { type:"card", card:48, rate:0.05 }]
			}),
			new NPC( {
				id:3,
				name:"STR_NPC_JACK",
				iconID:'jack',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[8, 11, 15, 17, 18, 19, 20, 24, 25, 26, 27, 29, 30, 85],
				level:NPC.LEVEL_INITIATE,
				matchFee:10,
				MGPReward: { w:20, d:11, l:5 },
				itemRewards:[ { type:"card", card:29, rate:0.25 }, { type:"card", card:30, rate:0.25 }, { type:"card", card:85, rate:0.01 }]
			}),
			new NPC( {
				id:4,
				name:"STR_NPC_CLUB",
				iconID:'club',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[8, 11, 15, 17, 18, 19, 20, 24, 25, 26, 27, 29, 30, 86],
				level:NPC.LEVEL_INITIATE,
				matchFee:10,
				MGPReward: { w:25, d:13, l:6 },
				itemRewards:[ { type:"card", card:26, rate:0.33 }, { type:"card", card:27, rate:0.33 }, { type:"card", card:86, rate:0.02 }]
			}),
			new NPC( {
				id:5,
				name:"STR_NPC_MA_DINCHT",
				iconID:'ma-dincht',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 106],
				level:NPC.LEVEL_INITIATE,
				matchFee:10,
				MGPReward: { w:25, d:13, l:6 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 },  { type:"card", card:26, rate:0.33 }, { type:"card", card:27, rate:0.33 }, {type:"card", card:106, rate:0.005 }]
			}),
			new NPC( {
				id:6,
				name:"STR_NPC_WATTS",
				iconID:'watts',
				rules:[tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 79],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:32, d:16, l:8 },
				itemRewards:[{ type:"card", card:79, rate:0.02 }]
			}),
			new NPC( {
				id:7,
				name:"STR_NPC_ZONE",
				iconID:'zone',
				rules:[tripleTriadRules.RULE_SAME],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 84],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:32, d:16, l:8 },
				itemRewards:[{ type:"card", card:84, rate:0.02 }]
			}),
			new NPC( {
				id:8,
				name:"STR_NPC_DIAMOND",
				iconID:'diamond',
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:36, d:18, l:9 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, { type:"card", card:67, rate:0.1 }, { type:"card", card:68, rate:0.1 }]
			}),
			new NPC( {
				id:9,
				name:"STR_NPC_SPADE",
				iconID:'spade',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 98],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:40, d:20, l:10 },
				itemRewards:[{ type:"card", card:98, rate:0.01 }]
			}),
			new NPC( {
				id:10,
				name:"STR_NPC_TREPIES",
				iconID:'trepies',
				rules:[tripleTriadRules.RULE_ALL_OPEN, tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 104],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:44, d:22, l:11 },
				itemRewards:[{ type:"card", card:104, rate:0.01 }]
			}),
			new NPC( {
				id:11,
				name:"STR_NPC_CARAWAY",
				iconID:'caraway',
				rules:[tripleTriadRules.RULE_ELEMENTAL, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 107],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:48, d:24, l:12 },
				itemRewards:[{ type:"card", card:107, rate:0.01 }]
			}),
			new NPC( {
				id:12,
				name:"STR_NPC_MARTINE",
				iconID:'martine',
				rules:[tripleTriadRules.RULE_ELEMENTAL, tripleTriadRules.RULE_SUDDEN_DEATH],
				fetishesCards:[],
				cards:[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30],
				level:NPC.LEVEL_AVERAGE,
				matchFee:15,
				MGPReward: { w:48, d:24, l:12 },
				itemRewards:[]
			}),
			new NPC( {
				id:13,
				name:"STR_NPC_PIET",
				iconID:'piet',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,95],
				level:NPC.LEVEL_ADVANCED,
				matchFee:20,
				MGPReward: { w:54, d:27, l:13 },
				itemRewards:[{ type:"card", card:95, rate:0.01 }]
			}),
			new NPC( {
				id:13,
				name:"STR_NPC_ODINE",
				iconID:'odine',
				rules:[tripleTriadRules.RULE_ELEMENTAL, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_SUDDEN_DEATH],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,100],
				level:NPC.LEVEL_ADVANCED,
				matchFee:20,
				MGPReward: { w:54, d:27, l:13 },
				itemRewards:[{ type:"card", card:100, rate:0.01 }]
			}),
			new NPC( {
				id:14,
				name:"STR_NPC_JOCKER",
				iconID:'jocker',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_SUDDEN_DEATH],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,91],
				level:NPC.LEVEL_ADVANCED,
				matchFee:20,
				MGPReward: { w:54, d:27, l:13 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, { type:"card", card:91, rate:0.01 }]
			}),
			new NPC( {
				id:15,
				name:"STR_NPC_FLO",
				iconID:'flo',
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,105],
				level:NPC.LEVEL_ADVANCED,
				matchFee:20,
				MGPReward: { w:54, d:27, l:13 },
				itemRewards:[{ type:"card", card:105, rate:0.01 }]
			}),
			new NPC( {
				id:16,
				name:"STR_NPC_DOBE",
				iconID:'dobe',
				rules:[tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,83],
				level:NPC.LEVEL_ADVANCED,
				matchFee:20,
				MGPReward: { w:54, d:27, l:13 },
				itemRewards:[{type:"card",  card:83, rate:0.02 }]
			}),
			new NPC( {
				id:17,
				name:"STR_NPC_EDEA",
				iconID:'edea',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,108],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"card", card:108, rate:0.01 }]
			}),
			new NPC( {
				id:18,
				name:"STR_NPC_KING",
				iconID:'king',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,108],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, {type:"card",  card:108, rate:0.01 }]
			}),
			new NPC( {
				id:19,
				name:"STR_NPC_CID",
				iconID:'cid',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,109],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"card", card:109, rate:0.01 }]
			}),
			new NPC( {
				id:20,
				name:"STR_NPC_HEART",
				iconID:'heart',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_PLUS],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,89],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"potion", potion:'MGP_BOOST', rate:1 }, {type:"card",  card:89, rate:0.01 }]
			}),
			new NPC( {
				id:21,
				name:"STR_NPC_ELLONE",
				iconID:'ellone',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_SAME, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_PLUS, tripleTriadRules.RULE_ELEMENTAL],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,102],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"card", card:102, rate:0.01 }]
			}),
			new NPC( {
				id:22,
				name:"STR_NPC_LAGUNA",
				iconID:'laguna',
				rules:[tripleTriadRules.RULE_ELEMENTAL, tripleTriadRules.RULE_SAME_WALL, tripleTriadRules.RULE_SUDDEN_DEATH],
				fetishesCards:[],
				cards:[33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,110],
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:110, d:40, l:20 },
				itemRewards:[{ type:"card", card:110, rate:0.01 }]
			}),
			new NPC( {
				id:99,
				name:"STR_NPC_QUEEN_OF_CARDS",
				iconID:'queen-of-cards',
				rules:[tripleTriadRules.RULE_RANDOM, tripleTriadRules.RULE_ROULETTE],
				fetishesCards:[],
				cards:cards.getCardsByRarities([1,2,3,4], 'ff8_'),
				level:NPC.LEVEL_EXPERT,
				matchFee:30,
				MGPReward: { w:128, d:56, l:28 },
				itemRewards:[{ type:"card", card:110, rate:0.01 }]
			}),
		];
			
		public function NPCs() 
		{
			
		}
		
		public static function toListCollection():ListCollection {
			var lc:ListCollection = new ListCollection();
			LIST.sortOn(['difficulty', 'matchFee', 'name'], [Array.NUMERIC, Array.NUMERIC, Array.CASEINSENSITIVE]);
			var hour:uint = new Date().getHours() + 1;
			for each(var npc:NPC in NPCs.LIST) {
				if (npc.availability && uint(npc.availability.begins) > 0 && uint(npc.availability.ends) > 0) {
					if (uint(npc.availability.begins) > hour < uint(npc.availability.ends)) {
						if ( (hour >= uint(npc.availability.begins) && hour <= 24 ) || (hour > 0 && hour < uint(npc.availability.ends))) {
							lc.push(npc.toListItemDatas());
						}
					} else {
						if (hour >= uint(npc.availability.begins) && hour < uint(npc.availability.ends)) {
							lc.push(npc.toListItemDatas());
						}
					}
				} else {
					lc.push(npc.toListItemDatas());
				}
			}
			return lc;
		}
	}

}